name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: idriss98/flaskapp:latest

  deploy:
    name: Deploy to Self-Hosted Server
    runs-on: ubuntu-kuber
    needs: build-and-push

    steps:
      - name: Pull and Run Docker Container
        run: |
          docker pull idriss98/flaskapp:latest
          docker stop flask || true
          docker rm flask || true
          docker run -d --name flask -p 80:5000 idriss98/flaskapp:latest
