name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        if: secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != ''
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: idriss98/flaskapp:latest

  deploy:
    name: Deploy to Self-Hosted Server
    runs-on: [self-hosted, ubuntu-kuber]
    needs: build-and-push

    steps:
      - name: Verify Docker Installation
        run: |
          if ! command -v docker &> /dev/null; then
              echo "::error::Docker is not installed on the runner"
              exit 1
          fi
          docker --version

      - name: Login to Docker Hub (if private image)
        if: env.DOCKER_REGISTRY_USERNAME != '' && env.DOCKER_REGISTRY_PASSWORD != ''
        run: |
          echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin

      - name: Pull and Run Docker Container
        run: |
          docker pull idriss98/flaskapp:latest || {
              echo "::error::Failed to pull Docker image"
              exit 1
          }
          
          docker stop flask || true
          docker rm flask || true
          
          docker run -d --name flask -p 80:5000 idriss98/flaskapp:latest || {
              echo "::error::Failed to start container"
              exit 1
          }

      - name: Verify Container Health
        run: |
          sleep 5
          if ! docker ps --filter "name=flask" --filter "status=running" | grep flask; then
              echo "::error::Container is not running"
              exit 1
          fi